version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${APP_PORT}:${APP_PORT}" # Прокидываем порт из .env
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: mobile_app/Dockerfile
    container_name: frontend
    ports:
      - "8000:80" # Порт для фронтенда остается фиксированным
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432" # Прокидываем порт для базы из .env

volumes:
  postgres_data:
